# Generated by Django 5.1.1 on 2024-09-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='lot_size',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_images/'),
        ),
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Trading Journal', max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='accounts.tradingaccount')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.accountjournal'),
        ),
    ]
