# Generated by Django 5.1.1 on 2024-10-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_journalentry_lot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
