# Generated by Django 5.1.1 on 2024-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_journalentry_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='direction',
            field=models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT')], max_length=5, null=True),
        ),
    ]
