# Generated by Django 5.1.1 on 2024-10-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_journalentry_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='direction',
            field=models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT')], max_length=5),
        ),
    ]
