# Generated by Django 5.1.1 on 2024-12-11 09:01

from django.db import migrations

def migrate_images(apps, schema_editor):
    JournalEntry = apps.get_model('journal', 'JournalEntry')
    JournalImage = apps.get_model('journal', 'JournalImage')

    for entry in JournalEntry.objects.all():
        if entry.image: 
            JournalImage.objects.create(entry=entry, image=entry.image)

class Migration(migrations.Migration):


    dependencies = [
        ('journal', '0010_journalentry_textarea_alter_journalentry_direction'),
    ]

    operations = [
        migrations.RunPython(migrate_images)
    ]
