# Generated by Django 5.1.1 on 2024-12-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_journalimage'),
        ('journal', '0012_auto_20241211_1101'),
    ]

    operations = [
    ]
