# Generated by Django 5.1.1 on 2024-12-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_merge_0011_journalimage_0012_auto_20241211_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='image',
        ),
    ]
