# Generated by Django 5.1.1 on 2024-12-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_remove_journalentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalimage',
            name='image',
        ),
        migrations.AddField(
            model_name='journalimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
