# Generated by Django 5.1.1 on 2024-12-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_remove_journalimage_image_url_journalimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalimage',
            name='image',
            field=models.ImageField(upload_to='journal_images/'),
        ),
    ]
