# Generated by Django 5.1.1 on 2024-12-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_alter_journalimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalimage',
            name='image',
        ),
        migrations.AddField(
            model_name='journalimage',
            name='image_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
