# Generated by Django 5.1.1 on 2024-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=9)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broker', models.CharField(choices=[('IG GROUP', 'IG Group'), ('OANDA', 'OANDA'), ('XM', 'XM'), ('ETORO', 'eToro'), ('SAXO BANK', 'Saxo Bank'), ('PEPPERSTONE', 'Pepperstone'), ('INTERACTIVE BROKERS', 'Interactive Brokers'), ('AVATRADE', 'AvaTrade'), ('FP MARKETS', 'FP Markets')], max_length=50)),
            ],
        ),
    ]
